In [31]:
# Read data from file
import numpy as np
def read(filename):
    with open(filename, 'r') as f:
        N, K = map(int, f.readline().split())
        d = [0] + list(map(float, f.readline().split()))
        t = np.zeros((N + 1, N + 1))
        for i in range(N + 1):
            t[i] = list(map(float, f.readline().split()))

    return N, K, d, t

def creat_cost(N, d, t):
    cost_matrix = np.zeros((N + 1, N + 1))
    for i in range(N + 1):
        for j in range(N + 1):
            if i != j:
                cost_matrix[i][j] = d[j] + t[i][j]

    return cost_matrix


file_path = "data\\" + "data_5_2.txt"
N, K, d, t = read(file_path)
cost_matrix = creat_cost(N, d, t)
visited = np.zeros(N + 1)
x = np.zeros(1000, dtype= int)
y = np.zeros(100, dtype = int)
x_best = x
y_best = y
f_best = 1e9
f_current = 0
numSegments = 0


def solution():

    for i in range(1, K + 1):
        print(y[i], end = " ")
        temp = x[y[i]]
        while temp != 0:
            print(temp, end = " ")
            temp = x[temp]
        print()
    print("Ketthuc")

def checkX(v, i, k):
    if v == 0:
        return True
    if visited[v] == 1:
        return False
    return True
    
def checkY(i, k):

    if k == K:
        if i == 0:
            return False
    return True

def TryX( i, k, numSegments, x, y, visited):
    # Dieu kien nhanh can
    for v in range(0, N + 1):
        if checkX(v, i, k):
            x[i] = v
            visited[v] = 1
            numSegments = numSegments + 1
            if v == 0:
                if k == K:
                    if sum(visited[1: N + 1]) == N:
                        print(visited)
                        solution()
                else:
                    TryX(y[k+1], k + 1, numSegments, x, y, visited)
            else:
                TryX(v, k, numSegments, x, y, visited)

            visited[v] = 0
            print(visited)
            numSegments = numSegments - 1

def TryY( k, numSegments, x, y, visited):
        for i in range(y[k-1], N - K + sum(1 for value in x[:k] if value != 0) + 1):
            if checkY(i, k):
                y[k] = i
                visited[i] = 1
                numSegments = numSegments + 1
                if k == K:
                    first = 1
                    while y[first] == 0:
                        first = first + 1
                    TryX(y[first], 1, numSegments, x, y, visited)
                else:
                    TryY(k + 1, numSegments, x, y, visited)
                
                visited[i] = 0
                numSegments = numSegments - 1
    
TryY(1, 0, x, y, visited)
                



[0. 1. 0. 0. 0. 0.]
[0. 1. 1. 0. 0. 0.]
[0. 1. 1. 1. 0. 0.]
[0. 1. 1. 1. 1. 0.]
[1. 1. 1. 1. 1. 1.]
0 
1 2 3 4 5 
Ketthuc
[0. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 0.]
[0. 1. 1. 1. 0. 0.]
[0. 1. 1. 1. 0. 1.]
[1. 1. 1. 1. 1. 1.]
0 
1 2 3 5 4 
Ketthuc
[0. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 0. 1.]
[0. 1. 1. 1. 0. 0.]
[0. 1. 1. 0. 0. 0.]
[0. 1. 1. 0. 1. 0.]
[0. 1. 1. 1. 1. 0.]
[1. 1. 1. 1. 1. 1.]
0 
1 2 4 3 5 
Ketthuc
[0. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 0.]
[0. 1. 1. 0. 1. 0.]
[0. 1. 1. 0. 1. 1.]
[1. 1. 1. 1. 1. 1.]
0 
1 2 4 5 3 
Ketthuc
[0. 1. 1. 1. 1. 1.]
[0. 1. 1. 0. 1. 1.]
[0. 1. 1. 0. 1. 0.]
[0. 1. 1. 0. 0. 0.]
[0. 1. 1. 0. 0. 1.]
[0. 1. 1. 1. 0. 1.]
[1. 1. 1. 1. 1. 1.]
0 
1 2 5 3 4 
Ketthuc
[0. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 0. 1.]
[0. 1. 1. 0. 0. 1.]
[0. 1. 1. 0. 1. 1.]
[1. 1. 1. 1. 1. 1.]
0 
1 2 5 4 3 
Ketthuc
[0. 1. 1. 1. 1. 1.]
[0. 1. 1. 0. 1. 1.]
[0. 1. 1. 0. 0. 1.]
[0. 1. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 1. 0. 1. 0. 0.]
[0. 1. 1. 1. 0. 0.]
[0. 1. 1. 1. 1. 0.]
[1. 1. 1. 1. 1. 1.]
0 
1 3 2

In [36]:
a = 10
x = np.zeros(10)
def cong():
    x[1] = 10
    print(x)
cong()
x

[ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]


array([ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])